Update nf-core/demultiplex to 1.5.4
NationalGenomicsInfrastructure/miarka-provision pull request #298
Opened 2024-12-17 16:15 UTC by Aratz

When running bcl2fastq, nf-core/demultiplex uses the input directory as work directory, this means that if fastq files are already there from a previous run, they will be picked up by nextflow and written to the pipeline output directory.

This might trip re-runs (see https://github.com/nf-core/demultiplex/issues/106) and downstream analysis pipelines (such as seqreports).

This was fixed in https://github.com/nf-core/modules/pull/6112 and included in nf-core/demultiplex v1.5.0 by restricting bcl2fastq's output to a special `output` directory, which makes it easier to only select these files when using the `publishDir` directive.

This PR updates nf-core/demultiplex to the latest version and refines the `publishDir` pattern.

2024-12-18 07:26 UTC, matrulda approved these changes
Awesome! Looks good to me.

2024-12-18 10:23 UTC, slohse requested changes
Looks good, but found a small syntax error :)

2024-12-18 10:23 UTC, slohse commented on roles/arteria-sequencing-report-ws/templates/nextflow_configs/demultiplex.config.j2
> +    id 'nf-schema@{{ nf_schema_version }}
missing closing `'`

2024-12-20 07:48 UTC, Aratz commented on roles/arteria-sequencing-report-ws/templates/nextflow_configs/demultiplex.config.j2
> +    id 'nf-schema@{{ nf_schema_version }}
Good catch :facepalm:

2024-12-20 07:53 UTC, slohse approved these changes

2024-12-20 09:21 UTC, merged