WIP: Dev 1737 refactor nextflow role
NationalGenomicsInfrastructure/miarka-provision pull request #30
Opened 2022-02-25 14:03 UTC by GitEdvard

Purpose:
The seqreports role is referred to from sysman, when provisioning the seqreports-dev machine. However, it's not possible to run Seqreports-dev as long as nextflow is dependent on ngi_pipeline. Therefore, reverse the dependencies between nextflow and ngi_pipeline roles. 

Details:
A portion of the tasks within the nextflow role is related to update e.g. sourceme_common file, which in turn is created by the ngi_pipeline. These tasks (that is configuring environment variables)  are moved to the ngi_pipeline role and gathered in the file "config_nextflow.yml". 

Validations:
The nextflow role had dependencies on ngi_pipeline and nf-core roles. I have run ngi_pipeline role before and after this refactoring, without errors. Regarding the nf-core role, I cannot go past the "nf-core download rnaseq v3.0" task, neither before or after the refactoring.

2022-03-03 09:47 UTC, b97pla requested changes
Great work! I think this largely looks good. 

However, I would object to the part where `ngi_pipeline` role adds the `nextflow` role's parameters to the source files etc. I think that is the wrong place for that. Basically, as it is now, this is required because the `ngi_pipeline` role is probably not the proper place for these files to be initially set up in the first place.

I would suggest, either creating a separate role that will set up the common files needed for several roles (`sourceme_...`, `deployed_tools...`, `create_directory...` etc.) or to just move these tasks from `ngi_pipeline` to `anaconda` so that they are in place when the `nextflow`  role is run. 

What do you think?

2022-03-04 14:54 UTC, GitEdvard commented
Just a control question, could it ever be meaningful to run the new environment/configuration role together with another role which is not the ngi-pipeline role? Generally I think it's a good approach to wait to do such refactoring until we have a specific need for it, in which time we probably have more detailed knowledge of the requirements. I have nothing against to do this refactoring now though (you might sit on knowledge that I don't have). 

Moving these tasks to anaconda shouldn't be feasible for the sake of seqreports role, which is dependent on anaconda as well.

2022-03-07 10:41 UTC, b97pla commented
I would say so. All roles depend on `deployed_tools` and several roles use the other files as well, so it's not entirely logical that they are set up in the `ngi_pipeline` role to begin with and it could make sense to have a dedicated role set these up.

My thinking with `anaconda` was precisely that all roles depend on it so it will always be run first and therefore it would be a shortcut to set up the files in that role. But I may be misunderstanding the premise for the `seqreports` role on `sysman`. Also, I'm more in favor of my first suggestion..

2022-03-07 12:16 UTC, GitEdvard commented
Ok, thanks for the clarification. I refactor the configuration into a separate role.

2022-03-07 14:20 UTC, GitEdvard commented
The refactoring is done :heavy_check_mark:  

* configure_base_sw runs without ngi_pipeline role. 
* ngi_pipeline is dependent on configure_base_sw (in meta dir), and runs without errors. 

Do you think the name configure_base_sw is relevant? Please check if all things is OK.

2022-03-07 14:22 UTC, GitEdvard commented
Please not that this PR goes to the staging branch 1737-seqreports-branch. I don't want to crash the current validation. Otherwise, I think this PR should go to the main branch (monthly?) rather quickly.

2022-03-08 14:24 UTC, b97pla commented on roles/configure_base_sw/tasks/main.yml
> +- name: Add py3 anaconda env path to sourceme script for {{ site }}
move to `ngi_pipeline`

2022-03-08 14:25 UTC, b97pla commented on roles/configure_base_sw/tasks/main.yml
> +- name: Try getting anaconda version
move to `anaconda`

2022-03-08 14:25 UTC, b97pla commented on roles/configure_base_sw/tasks/main.yml
> +- name: Store anaconda version in deployment
move to `anaconda`

2022-03-09 08:20 UTC, b97pla commented on install.yml
> -    - { role: nextflow, tags: nextflow }
this role should not be removed

2022-03-09 08:23 UTC, b97pla commented on roles/configure_base_sw/tasks/main.yml
> +- name: Create miarka config
the template should remain in the Nextflow role

2022-03-09 08:24 UTC, b97pla commented on roles/nextflow/meta/main.yml
> -  - { role: ngi_pipeline, tags: ngi_pipeline, environment: "{{ tools_path }}" }
it should depend on `configure_base_sw`

2022-03-09 08:26 UTC, b97pla commented on roles/nf-core/meta/main.yml
> +  - { role: ngi_pipeline, tags: ngi_pipeline, environment: "{{ tools_path }}" }
I believe it should be depending on `Nextflow` and `anaconda`

2022-03-09 08:26 UTC, b97pla commented on roles/ngi_pipeline/meta/main.yml
> +  - { role: configure_base_sw, tags: configure_base_sw }
also `anaconda`

2022-03-09 08:29 UTC, b97pla commented on roles/configure_base_sw/README.md
> +Configure the base software (currently nextflow and anaconda), and setup environment variables for these. Creates file for deployed_tool_versions, which is used by most other roles. Deploys sourceme_
```suggestion
Creates file for deployed_tool_versions, which is used by most other roles. Deploys sourceme_common.sh and sourceme_site.sh.
```

2022-03-09 14:30 UTC, GitEdvard commented
Now, let's give it another try :)

2022-03-10 08:53 UTC, b97pla approved these changes
:+1: great work, I'm happy 😃

2022-03-10 08:53 UTC, b97pla commented on roles/ngi_pipeline/tasks/main.yml
> +- name: Add py3 anaconda env path to sourceme script for {{ site }}
personally, I would put this task after the environment has been created but it's not that important

2022-03-10 08:53 UTC, merged